from __future__ import annotations
from typing import NewType

PlayerId = NewType("PlayerId", str)
RoomId = NewType("RoomId", str)
CardId = NewType("CardId", str)

# --- Standardized Constants ---

# Monsters
MONSTER_ID_REINA = "MONSTER:REINA_HELADA"
MONSTER_ID_ARAÑA = "MONSTER:ARAÑA"
MONSTER_ID_DUENDE = "MONSTER:DUENDE"
MONSTER_ID_VIEJO = "MONSTER:VIEJO_DEL_SACO"
MONSTER_ID_TUE_TUE = "MONSTER:TUE_TUE" # Only Omen/Event log
MONSTER_ID_ICE_SERVANT = "MONSTER:ICE_SERVANT"

# Omens
OMEN_ID_REINA = "OMEN:REINA_HELADA"
OMEN_ID_TUE_TUE = "OMEN:TUE_TUE"

# Special Rooms
SPECIAL_ROOM_TABERNA = "TABERNA"
SPECIAL_ROOM_MOTEMEY = "MOTEMEY"
SPECIAL_ROOM_ARMERIA = "ARMERIA"
SPECIAL_ROOM_PUERTAS = "PUERTAS_AMARILLO"
SPECIAL_ROOM_CAMARA = "CAMARA_LETAL"
SPECIAL_ROOM_SALON = "SALON_BELLEZA"
SPECIAL_ROOM_MONASTERIO = "MONASTERIO_LOCURA"
